name: Deploy demo to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      # Base path like "/<REPO_NAME>/" for GitHub Pages
      BASE_PATH: "/${{ github.event.repository.name }}/"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Enable Corepack (uses packageManager)
        run: corepack enable

      - name: Install deps (workspace)
        run: pnpm install

      - name: Build workspace (core + data)
        run: pnpm -r --filter which_carrier --filter which_carrier-data build

      - name: Build web demo (Vite)
        working-directory: packages/web
        run: pnpm build

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/web/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
